// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIM8W2dJXq2wtr2gb4cSp4pHN5lOB1ER4',
    appId: '1:608649528890:web:efa3b4b6b32d7395f21703',
    messagingSenderId: '608649528890',
    projectId: 'moneybody',
    authDomain: 'moneybody.firebaseapp.com',
    storageBucket: 'moneybody.firebasestorage.app',
    measurementId: 'G-5DBEK4TJ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLV13sQ_BX4p69cpqMg00kXTtro65_L0A',
    appId: '1:608649528890:android:0ff14dc114f1a55ef21703',
    messagingSenderId: '608649528890',
    projectId: 'moneybody',
    storageBucket: 'moneybody.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXdVIzVY5-tdjTswMPxE3CmBO6WQepJc',
    appId: '1:608649528890:ios:2bca9c99f132a66ef21703',
    messagingSenderId: '608649528890',
    projectId: 'moneybody',
    storageBucket: 'moneybody.firebasestorage.app',
    androidClientId: '608649528890-svsah3tpqushl714qocb65t4bl165g0c.apps.googleusercontent.com',
    iosClientId: '608649528890-428302sr0fgt1o2rnraf78726i7lokng.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXdVIzVY5-tdjTswMPxE3CmBO6WQepJc',
    appId: '1:608649528890:ios:2bca9c99f132a66ef21703',
    messagingSenderId: '608649528890',
    projectId: 'moneybody',
    storageBucket: 'moneybody.firebasestorage.app',
    androidClientId: '608649528890-svsah3tpqushl714qocb65t4bl165g0c.apps.googleusercontent.com',
    iosClientId: '608649528890-428302sr0fgt1o2rnraf78726i7lokng.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIM8W2dJXq2wtr2gb4cSp4pHN5lOB1ER4',
    appId: '1:608649528890:web:b54e7a8b46718e0ef21703',
    messagingSenderId: '608649528890',
    projectId: 'moneybody',
    authDomain: 'moneybody.firebaseapp.com',
    storageBucket: 'moneybody.firebasestorage.app',
    measurementId: 'G-SBZHZQ6WLL',
  );

}